BAMRU-Tech/bamru_net

bamru_net/urls.py, main/templates/index.html, main/views/main_views.py
Avoids an unsightly 404, and lets you access the navbar to find what
you're looking for.
=> Add empty index page

bamru_net/urls.py, main/static/css/style.css, main/static/js/dynamic_formset.js, main/templates/member_detail.html, main/templates/member_form.html, main/views/member_views.py
Things not done here:
* Make the forms prettier. (Getting a one-line form by using the table markup without a surrounding `<table>` element is shameful and ugly.)
* Phone/email "pagable" settings should be gated by confirmation that the page will be received (and pagable phones/emails shouldn't be editable through this UI).
* Tests.
=> Member edit page

.circleci/config.yml, message/models.py, message/tests.py
Add test using Twilio test credentials.
=> Add more error checking to outgoing SMS, fix status length.

bamru_net/urls.py, main/admin.py, main/models/member.py, main/serializers.py, main/templates/do_plan.html, main/tests/test_do.py, main/views/api_views.py, main/views/do_views.py
- Compute DO shift start and end
- Add DO API
- Add interactive scheduling to the DO planning view
=> Round out DO scheduling

bamru_net/urls.py
How did github even let these be committed?
=> Fix up leftover merge conflict markers

main/views/event_views.py
I spent some time looking at javascript libraries for date/time picking,
but then I discovered that these input types exist, and modern browsers
have totally reasonable behaviour for them. In particular, on mobile,
this is probably ideal behaviour: at least with Chrome on Android, the
these invoke the system's standard date and time pickers!
This commit also includes form logic to validate that the finish isn't
before the start for this particular usage. It's possible to avoid this
check via the REST API, and I can't find a good way to implement this
validation once so that it applies everywhere.
=> Use html input type="date"/"time" in event edit

message/forms.py, message/templates/message_compose.html, message/views.py
- Hide fields that one one will ever need to change
- Indicate period and RSVP type above form
- Add character counter
=> UI work on message compose

main/templates/event_detail.html
=> Fix test message - #130

deploy/provision.yml
=> Redirect non-SSL to SSL - #26

bamru_net/urls.py, main/templates/index.html, main/templates/message_add.html, main/templates/navbar.html, main/views/event_views.py, main/views/member_views.py, main/views/message_views.py
=> Devc merge

main/serializers.py, main/views/api_views.py
=> Add filter on published - #133

main/models/message.py
=> Add uuid to email subject #161

bamru_net/settings.py, bamru_net/urls.py, main/oidc_provider_settings.py, requirements.txt
Set up for #192, can be extended for #179
=> Add oauth/openid provider

main/templates/message_detail.html, main/views/message_views.py
=> Add message stats #269

main/templates/cert_list.html
=> Changed sort order for cert list to use status

main/models/message.py
=> Shorten email subject slug - #300

main/oidc_provider_settings.py
=> Fix wiki login for those with spaces in their names #339

main/views/message_views.py
=> Fix 'no' RSVP handling to remove times #337

bamru_net/urls.py, main/templates/message_add.html, main/templates/navbar.html, main/views/message_views.py
=> Add test page to yourself #344

bamru_net/settings.py, bamru_net/urls.py, main/templates/registration/password_reset_complete.html, main/templates/registration/password_reset_confirm.html, main/templates/registration/password_reset_done.html, main/templates/registration/password_reset_email.html, main/templates/registration/password_reset_form.html, main/views/__init__.py, main/views/auth_views.py
=> Add password reset #281

main/models/member.py, main/serializers.py, main/templates/message_add.html, main/templates/message_detail.html, main/templates/period_participant_add.html
Backend for #292 along with initial front-end
=>  Add is_unavailable to member, initial display of availability on pages

main/templates/message_detail.html
=> Auto refresh sort and repage link

main/templates/message_detail.html
Is testing "sent == rsvp'd" the right test?
=> Add check on repage when everyone has responded

main/templates/event_detail.html, main/templates/member_availability_list.html, main/templates/member_cert_list.html, main/templates/member_do_availability_list.html
=> Single-Click "left now", etc for DO under More->Set times

main/templates/event_detail.html
=> Added simple map link on event detail

main/templates/available_list.html
=> Fixed availability filter

main/templates/member_list.html
=> Might fix 'click to dial' on iphone

main/templates/base_ftable.html, main/templates/event_detail.html, main/templates/event_list.html
=> Added attend button and fixes for exports

main/templates/base_ftable.html, main/templates/event_detail.html
=> Show search button on larger screen (hidden on small screen)

main/templates/base_generic.html
This was causing the comment text to display on the site.
=> Fix line-wrapped comment

main/views/message_views.py
=> Invite all, even those who are already in the event #443

main/templates/reports/index.html, main/views/report_views.py
=> Add UI to select dates for reports. #442

bamru_net/urls.py, main/templates/reports/index.html, main/views/report_views.py
=> Add report of errors and warnings in past events. #433

main/tasks.py
=> Automatically set sign in and out times for meetings. #434

main/templates/event_detail.html, main/templates/message_detail.html
=> Add copy email addresses for members of OP

main/templates/event_detail.html
=> Modified email copy to use directly with gmail (removed title and hdr)

main/templates/event_list.html, main/templates/member_do_availability_list.html, main/templates/message_add.html
=> Add indeterminate display for DO availability when null

main/templates/event_detail.html
=> Allow OL and AHC to be set (regression)XS

main/templates/message_list.html, main/views/message_views.py
=> Add pagination to message list. #475

main/models/member.py, main/tests/test_do.py
Fix sentry issue DJANGO-PROD-57 - Expected 1 DO scheduled, got 0
=> Fix calculation of current DO week, quarter, & year. Add test.

main/templates/member_detail.html
=> Show all certs not just first of a cert type

main/templates/base_ftable.html, main/templates/member_list.html
Sample output:
4 TM, 20 FM, 28 R, 25 T, 2 A (79 total)
=> Add summary with numbers of members of each status.

main/templates/event_list.html
=> Show events for next year. #473

main/templates/base_ftable.html, main/templates/base_generic.html, main/templates/base_table.html, main/templates/event_list.html
There seems to be a bug in datatables.  This is a workaround for now. UI impact of the workaround will probably go unnoticed.
=> Fixed #522 ColVis and updated datatables code

main/models/member.py, main/views/member_views.py
=> Query fixes followup

main/templates/event_detail.html
dynamically disable the add button if the logged in user is already in an event. Also fix a typo
=> Resolve Duplicate Attendees Alert

main/views/report_views.py
Added a single condition per member to check if attended > 0 events and incrementing the unit total of participants, if so.
Changed some variable names for readability.
=> Deduplicate members when totalling members
